name: "[Common] Get Operator versions"

on:
  workflow_call:
    outputs:
      operator_version_latest:
        value: ${{ jobs.get_operator_versions.outputs.operator_version_latest }}
      operator_version_next:
        value: ${{ jobs.get_operator_versions.outputs.operator_version_next }}
      cheese:
        value: ${{ jobs.get_operator_versions.outputs.cheese }}

jobs:
  get_operator_versions:
    runs-on: ubuntu-latest

    outputs:
      operator_version_latest: ${{ steps.set_output_parameters.outputs.latest_tag }}
      operator_version_next: ${{ steps.set_output_parameters.outputs.next_tag }}
      cheese: "cheese"

    steps:
      # ===============================
      # Checkout code to get tags
      # -------------------------------
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      # ===============================

      # ===============================
      # Construct next version
      # -------------------------------
      # Read the latest semver tag
      - name: Get latest tag
        id: latest_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          fallback: 0.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Increment the latest semver tag for release builds
      - name: Read semver version
        id: next_tag
        uses: WyriHaximus/github-action-next-semvers@v1.2.1
        with:
          version: ${{ steps.latest_tag.outputs.tag }}

      # Export parameters
      - name: Set output parameters
        id: set_output_parameters
        run: |
          echo "latest_tag=${{ steps.latest_tag.outputs.tag }}" >> $GITHUB_OUTPUT
          echo "next_tag=${{ steps.next_tag.outputs.patch }}" >> $GITHUB_OUTPUT
      # ===============================
